### ISSUE TITLE
Configurations and documentation

### ISSUE THREAD

**Issue by lamb0tiana** [lengthylyova/gh-contrib-graph#14]
Hi! Thank you for your great work. 
It would be even better if there were options for customization, such as setting up a date filter and applying custom styles.

**Comment by lyova24** [comment]
Hi @lamb0tiana!

How do you imagine this? As some html attributes or complete buttons for the client?

**Comment by lamb0tiana** [comment]
@lengthylyova ,  I thought initializing with some configurations like this:

```gh({...some_config})```

would allow customization of the theme (dark/light), for example. Otherwise, you would need to modify gh.css in the assets.

**Comment by lyova24** [comment]
> @lengthylyova , I thought initializing with some configurations like this:
> 
> `gh({...some_config})`
> 
> would allow customization of the theme (dark/light), for example. Otherwise, you would need to modify gh.css in the assets.

What do you think about realization using HTML attributes?

---

**html**
```html
<!-- for example theme attribute with "light" or "dark" options -->
<div id="gh" data-login="YOUR_GITHUB_LOGIN" theme="light"></div>
```
**css**
```css
#gh[theme="light"] {
    something: value;
}
```

**Comment by lyova24** [comment]
```
408 Request Timeout
```
